export interface Color {
  '--ursa-color-scheme': string;
  '--ursa-bg-primary': string;
  '--ursa-backdrop': string;
  '--ursa-text-primary': string;
  '--ursa-text-secondary': string;
  '--ursa-btn-primary': string;
  '--ursa-btn-primary-hovered': string;
  '--ursa-btn-basic': string;
  '--ursa-btn-alert': string;
  '--ursa-btn-alert-hovered': string;
  '--ursa-btn-disabled': string;
  '--ursa-link-primary': string;
  '--ursa-link-primary-hovered': string;
  '--ursa-border-primary': string;
  '--ursa-border-secondary': string;
  '--ursa-nav-bg-primary': string;
  '--ursa-nav-item-bg-active': string;
  '--ursa-nav-item-bg-hovered': string;
  '--ursa-tag-bg-basic': string;
  '--ursa-tag-text': string;
  '--ursa-tab-selected': string;
  '--ursa-card-img-bg': string;
  '--ursa-badge-img-bg': string;
  '--ursa-accent-color': string;
  '--ursa-accent-color-hovered': string;
  '--ursa-white': string;
  '--ursa-black': string;
}
